# Generated by Django 4.0.5 on 2022-06-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_donor_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForOrgans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=6)),
                ('blood_group', models.CharField(max_length=100)),
                ('emergency_number', models.CharField(max_length=100)),
                ('emergency_address', models.CharField(max_length=100)),
                ('identity_card', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=100)),
                ('organs', models.JSONField()),
                ('tissue', models.JSONField()),
            ],
        ),
    ]
