# Generated by Django 4.0.5 on 2022-09-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blog_gallery_sponsore'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
